try
{
Promise
.
any
(
new
Test262Error
(
)
)
.
then
(
(
)
=
>
{
DONE
(
'
The
promise
should
be
rejected
but
was
resolved
'
)
;
}
(
error
)
=
>
{
assert
(
error
instanceof
TypeError
)
;
}
)
.
then
(
DONE
DONE
)
;
}
catch
(
error
)
{
DONE
(
The
promise
should
be
rejected
but
threw
an
exception
:
{
error
.
message
}
)
;
}
