assert
.
throws
(
Test262Error
function
(
)
{
try
{
throw
new
Error
(
)
;
}
catch
{
throw
new
Test262Error
(
)
;
}
}
)
;
reportCompare
(
0
0
)
;
